services:
  api:
    build: .
    container_name: petcare-api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes: 
      - .:/app
  db:
    image: postgres:15
    container_name: petcare-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
