"""Migration: added fields for account lockout system for invalid login attempts

Revision ID: 051bf6ddacf8
Revises: 45032be30594
Create Date: 2025-08-25 10:52:06.269521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "051bf6ddacf8"
down_revision: Union[str, Sequence[str], None] = "45032be30594"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_user",
        sa.Column(
            "failed_login_attempts", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "app_user", sa.Column("last_failed_login_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_user", "last_failed_login_at")
    op.drop_column("app_user", "failed_login_attempts")
    # ### end Alembic commands ###
