"""Migration: added last_login_at field in user model

Revision ID: 0520324f9a8c
Revises: 2ac9553742a8
Create Date: 2025-08-07 20:22:12.620973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '0520324f9a8c'
down_revision: Union[str, Sequence[str], None] = '2ac9553742a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("app_user")]

    if "last_login_at" not in columns:
        op.add_column("app_user", sa.Column(
            "last_login_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("app_user")]

    if "last_login_at" in columns:
        op.drop_column("app_user", "last_login_at")
    # ### end Alembic commands ###
