"""Initial migration

Revision ID: 2ac9553742a8
Revises: 
Create Date: 2025-07-30 21:59:27.320506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ac9553742a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM('USER', 'ADMIN', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('app_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('is_enabled', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column(
                        'hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('role', role_enum, nullable=False),
                    sa.Column('verification_code',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('verification_code_expires_at',
                              sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM('USER', 'ADMIN', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.drop_table('app_user')
    # ### end Alembic commands ###
