"""Migration: added deleted_at timestamp field to user model

Revision ID: 45032be30594
Revises: 775e8866b244
Create Date: 2025-08-20 17:06:12.331589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45032be30594'
down_revision: Union[str, Sequence[str], None] = '775e8866b244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'deleted_at')
    # ### end Alembic commands ###
