"""Migration: addend species and pet models and fixed created_at immutability error

Revision ID: 775e8866b244
Revises: 7fbd7ff009e1
Create Date: 2025-08-20 17:05:07.323875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '775e8866b244'
down_revision: Union[str, Sequence[str], None] = '7fbd7ff009e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_code'), 'species', ['code'], unique=True)
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'NOT_SPECIFIED', name='sex'), nullable=False),
    sa.Column('specie_id', sa.Integer(), nullable=True),
    sa.Column('breed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birthDate', sa.DateTime(), nullable=True),
    sa.Column('profileImageURL', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_index(op.f('ix_species_code'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
