"""Migration: added is_deleted field for soft-delete and deletion-flag in user model

Revision ID: 7fbd7ff009e1
Revises: 907706e5156f
Create Date: 2025-08-13 21:48:35.501318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbd7ff009e1'
down_revision: Union[str, Sequence[str], None] = '907706e5156f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'is_deleted')
    # ### end Alembic commands ###
